# This is an example of a ProjectHelmChart that would be deployed onto a Helm Project Operator
# instance that responds to helmApiVersion dummy.cattle.io/v1alpha1 and utilizes --project-label
#
# When --project-label is provided, spec.projectNamespaceSelector is ignored and can be omitted.
#
apiVersion: helm.cattle.io/v1alpha1
kind: ProjectHelmChart
metadata:
  name: test
  namespace: cattle-project-p-ranch
spec:
  helmApiVersion: dummy.cattle.io/v1alpha1
  values:
    data:
      hello: world