name: "[helm-locker] CI"

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x64
          - arm64
    runs-on : runs-on,image=ubuntu22-full-${{ matrix.arch }},runner=4cpu-linux-${{ matrix.arch }},run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name : Set up Go
        uses : actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run CI
        run: BUILD_TARGET=helm-locker make ci
